name: ğŸ¥ ssh-action-deploy
on: [push]

jobs:
  build:
    name: ğŸ•³ï¸ Ubuntu...
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’ Checkout do GitHub...
        uses: actions/checkout@v3
      
      - name: ğŸ“ Exportar IP do servidor
        run: |
          set -x
          echo "O IP do servidor Ã© ${{ secrets.IP }}"
      
      
      - name: ğŸŒˆ Deploy com SSH...
        uses: ./
        with:
          IP: ${{ secrets.IP }}  # Ainda usando o segredo diretamente para a aÃ§Ã£o
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          FOLDER: "/root/.deploy"
          RUN: "ls"
